apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress2
  namespace: test
spec:
  rules:
  - host: my-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app2
            port:
              number: 80
